#!/bin/bash
# SAK Editor - Help
# Quick reference for install/build commands

echo ""
echo "=========================================="
echo "SAK Editor - Quick Help"
echo "=========================================="
echo ""
echo "SETUP:"
echo "  ./install.sh          - Install all dependencies (Node.js, Rust, Tauri)"
echo ""
echo "DEVELOPMENT:"
echo "  npm run dev           - Start frontend dev server"
echo "  npm run tauri-dev     - Start Tauri dev mode (with GUI)"
echo ""
echo "BUILD:"
echo "  ./build.sh            - Build release version"
echo "  npm run build         - Alternative: use npm"
echo ""
echo "TEST:"
echo "  npm test              - Run all tests"
echo "  npm run test:e2e      - Run Playwright E2E tests"
echo ""
echo "FILES:"
echo "  After build, find executables in:"
echo "    - Linux: src-tauri/target/release/bundle/"
echo "    - macOS: src-tauri/target/release/bundle/"
echo "    - Windows: src-tauri\\target\\release\\bundle\\"
echo ""
echo "For more info: https://github.com/bluemot/sak-note"
echo "=========================================="
echo ""
